# General settings
gpu: 1
num_adv_epochs: 20
batch_size: 16
data_dir: ""
save_RL: 1
delete_temp_files: 0
adversarial: 0
disc_weight: 1
eval: 1

# Generator settings
gen_dir: "./save/huggan/gen/"
load_generator: 1
load_generator_path: "./codeparrot-results/finished_models/pretrained_disc/generator"
base_model: "codeparrot/codeparrot-small"
max_new_tokens: 20

# Discriminator settings
disc_dir: "./save/huggan/gen/"
load_discriminator: 0
load_discriminator_file: "./finished_models/pretrained_disc/discriminator.pt"
embed_dim: 64
filter_sizes: [1,2,3,4,5,6,7,8,9,10,15,20]
num_filters: [100,200,200,100,100,160,160]
dropout: 0.25
disc_lr: 0.01
num_samples: 32
clip_norm: 5.0